# Default parameters for Living Engine backtests
risk:
  RiskPercent: 0.015        # 1.5% of equity per trade
  RewardRisk: 2.3           # reward-to-risk multiple
  MaxDailyDrawdown: 0.065   # 6.5% clamp

entropy:
  CollapseThreshold: 0.09   # ΔΦ ≥ 0.09 ⇒ collapse regime (NP-hard wall)
  P_threshold: 0.045        # ΔΦ < 0.045 ⇒ P-like stability
  NP_threshold: 0.09        # ΔΦ > 0.045 and < 0.09 ⇒ NP drift
  RecoveryWindow: 12        # bars required under NP wall for recovery
  EntropyLookback: 20       # rolling window for ΔΦ averaging

signals:
  AtrPeriod: 14
  EmaFast: 12
  EmaSlow: 30
  StopAtrMult: 1.2
  TrailMult: 0.9

logging:
  ProofCapsuleFile: "proof_capsule.json"
  BlotterFile: "trades_blotter.csv"
  EnableProofBridge: true

sanctuary:
  EthicsEnabled: true
  ProofOfCare: true
