name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e .[dev]
      - run: leb --data data/sample/sample_ohlcv.csv --out runs/ci
      - run: cat runs/ci/metrics.json
      - run: pytest
